/******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Omar Anwar
 ******************************************************************************/

#include "Port.h"

/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/* AUTOSAR Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
		||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
#error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Port_PBcfg.c and Port.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
		||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
		||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
#error "The SW version of PBcfg.c does not match the expected version"
#endif

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
		PORT_PORTA_ID , PORT_PIN0_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTA_ID , PORT_PIN1_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTA_ID , PORT_PIN2_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTA_ID , PORT_PIN3_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTA_ID , PORT_PIN4_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTA_ID , PORT_PIN5_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTA_ID , PORT_PIN6_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTA_ID , PORT_PIN7_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,

		PORT_PORTB_ID , PORT_PIN0_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTB_ID , PORT_PIN1_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTB_ID , PORT_PIN2_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTB_ID , PORT_PIN3_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTB_ID , PORT_PIN4_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTB_ID , PORT_PIN5_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTB_ID , PORT_PIN6_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTB_ID , PORT_PIN7_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,

		PORT_PORTC_ID , PORT_PIN0_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTC_ID , PORT_PIN1_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTC_ID , PORT_PIN2_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTC_ID , PORT_PIN3_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTC_ID , PORT_PIN4_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTC_ID , PORT_PIN5_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTC_ID , PORT_PIN6_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTC_ID , PORT_PIN7_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,

		PORT_PORTD_ID , PORT_PIN0_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTD_ID , PORT_PIN1_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTD_ID , PORT_PIN2_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTD_ID , PORT_PIN3_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTD_ID , PORT_PIN4_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTD_ID , PORT_PIN5_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTD_ID , PORT_PIN6_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTD_ID , PORT_PIN7_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,

		PORT_PORTE_ID , PORT_PIN0_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTE_ID , PORT_PIN1_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTE_ID , PORT_PIN2_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTE_ID , PORT_PIN3_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTE_ID , PORT_PIN4_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTE_ID , PORT_PIN5_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,

		PORT_PORTF_ID , PORT_PIN0_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTF_ID , PORT_PIN1_ID, PORT_PIN_OUT, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTF_ID , PORT_PIN2_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTF_ID , PORT_PIN3_ID, PORT_PIN_IN, OFF, PORT_PIN_LEVEL_LOW, PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE,
		PORT_PORTF_ID , PORT_PIN4_ID, PORT_PIN_IN, PULL_UP, PORT_PIN_LEVEL_LOW,  PORT_PIN_MODE_DIO , PORT_CHANGEABLE, PORT_CHANGEABLE
};
